
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAMYAK & ATISHAY
 */
public class ACHIEVMENTS extends javax.swing.JFrame {

    /**
     * Creates new form ACHIEVMENTS
     */
    public ACHIEVMENTS(String un) {
        initComponents();
        L2.setText(un);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1282, 683));
        setMinimumSize(new java.awt.Dimension(1282, 683));
        setPreferredSize(new java.awt.Dimension(1282, 683));
        getContentPane().setLayout(null);

        jLabel11.setForeground(new java.awt.Color(0, 102, 255));
        jLabel11.setText("<<back to home");
        jLabel11.setMaximumSize(new java.awt.Dimension(1282, 683));
        jLabel11.setPreferredSize(new java.awt.Dimension(1282, 683));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 50, 110, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("1-Safety First: Elimination of unmanned level crossings, use of technology\n , online monitoring of rolling stock and switch over to German\n technology LHB coaches for safety of railway passengers\n2-Boosting ‘Make in India’ by indigenous manufacturing of semi high speed\n (160 Kmph) self-propelled Train 18 which boasts of ultra-modern features\n3-Push to capacity augmentation by commissioning strategic projects like\n Dedicated Freight Corridors (DFCs)\n4-Connecting North East: India’s longest rail-road bridge connecting Assam\n and Arunachal Pradesh\n5-Speedy and smooth passenger services via improved coaches and trains, UTS\n mobile app, VIKALP scheme and boosting digital transactions for online \nticket reservations\n6-Swachch Rail: Bio toilets, clean-my-coach SMS services, Coach Mitra\n initiatives for cleanliness in trains and railway stations\n7-65 stations across zonal railways have been beautified under station\n beautification initiative by using local art form, painting style, local themes\n8-Use of Robotics and industry 4.0 technologies in production units of \nIndian railways\n9-‘Mission Raftar’ to speed up, contribute and participate in the growth \nstory of India Brighter and energy efficient railways with 100% LED\n lights at all stations\n10-Promoting tourism through Vistadome coaches (see through coaches)");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(590, 100, 680, 540);

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 0, 31)); // NOI18N
        jLabel1.setText("SOME GOLDEN ACHIEVEMENTS IN THE HISTORY OF INDIAN RAILWAYS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 20, 1050, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/58694288_819134545112315_245119873419254439_n.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 540, 540);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mahkeo-Ef7C4bPDL4A-unsplash.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -4, 1280, 680);

        L2.setOpaque(true);
        getContentPane().add(L2);
        L2.setBounds(230, 10, 190, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
 new HOME(L2.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ACHIEVMENTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ACHIEVMENTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ACHIEVMENTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ACHIEVMENTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ACHIEVMENTS(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
