
import javax.swing.table.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAMYAK & ATISHAY
 */
public class ADD_PASSANGER extends javax.swing.JFrame {

    /**
     * Creates new form PAYMENT
     */
    public ADD_PASSANGER(String un1,int t,String dob,String src,String dst,String trn) {
        initComponents();
        L2.setText(""+t);L3.setText(""+un1);L4.setText(""+dob);L5.setText(""+src);L6.setText(""+dst);L7.setText(""+trn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AP = new javax.swing.JTable();
        T2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        R1 = new javax.swing.JRadioButton();
        R2 = new javax.swing.JRadioButton();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1026, 720));
        setMinimumSize(new java.awt.Dimension(1026, 720));
        setPreferredSize(new java.awt.Dimension(1026, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("ADD PASSENGER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 280, 60));

        AP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "GENDER", "AGE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AP);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 960, 130));

        T2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 290, 60));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 60, 50));

        T1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        getContentPane().add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 290, 60));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 100, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GENDER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 160, 50));

        buttonGroup1.add(R1);
        R1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        R1.setForeground(new java.awt.Color(255, 255, 255));
        R1.setText("MALE");
        R1.setOpaque(false);
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });
        getContentPane().add(R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 150, -1));

        buttonGroup1.add(R2);
        R2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        R2.setForeground(new java.awt.Color(255, 255, 255));
        R2.setText("FEMALE");
        R2.setOpaque(false);
        getContentPane().add(R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 180, 60));

        L2.setVisible(false);
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, 160, 50));

        L3.setVisible(false);
        getContentPane().add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 630, 50, 60));

        L6.setVisible(false);
        getContentPane().add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 770, 80, 20));

        L5.setVisible(false);
        getContentPane().add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 730, 80, 20));

        L4.setVisible(false);
        getContentPane().add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 690, 80, 30));

        L7.setVisible(false);
        getContentPane().add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 760, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1060, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("PROCEED");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 630, 50));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 352, 1050, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1050, 20));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" IRCTC NEXT GENERATION TICKET BOOKING SYSTEM");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 740, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1003073.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
String ge,nm,ag;int fa;
int f,nn,r,fare;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         DefaultTableModel mm=(DefaultTableModel) AP.getModel();
      
         if (R1.isSelected())
            
        {
        ge="male";
        }
     else
        {
        ge="female";
        }  
        nm=T1.getText();
        ag=T2.getText();
        Object row[]={nm,ge,ag};
        mm.addRow(row);
        T1.setText("");
         T2.setText("");
         R1.setSelected(false);
         R2.setSelected(false);

      
         //NEW DOUBT
        /*
         int i,a;
         String n,g;
         for(i=1;i<=r;i++)
         {
         n=(String) mm.getValueAt(i,1);
         g=(String) mm.getValueAt(i,2);
         a=(int) mm.getValueAt(i,3);
             System.out.println(n);
             System.out.println(a);
             System.out.println(g);
         }
         */
         
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         DefaultTableModel mm=(DefaultTableModel) AP.getModel();  
              int r=mm.getRowCount();
        fa=Integer.parseInt(L2.getText());
         int fare=fa*r;
         r=mm.getRowCount();
        String  un1= L3.getText();
        String  dob= L4.getText();
          String  src= L5.getText();
            String  dst= L6.getText();
          String  trn= L7.getText(); 
        new TICKET_INFO(fa,un1,dob,src,dst,trn,r).setVisible(true);
             this.dispose();
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1ActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD_PASSANGER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD_PASSANGER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD_PASSANGER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD_PASSANGER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD_PASSANGER(null,0,null,null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AP;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JRadioButton R1;
    private javax.swing.JRadioButton R2;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
