
import java.awt.Font;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.UIManager;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAMYAK & ATISHAY
 */
public class BOOK_MEALS extends javax.swing.JFrame {
int c,r,j,k,l,m,n,o,p,bf,lc,dn,bs;
String i=null;
    /**
     * Creates new form BOOK_MEALS
     */
    public BOOK_MEALS(String un) {
        initComponents();
        L2.setText(un);
        UIManager.put("OptionPane.messageFont", new Font("TIMES NEW ROMAN", Font.BOLD, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        BF = new javax.swing.JComboBox<>();
        DN = new javax.swing.JComboBox<>();
        LC = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA1 = new javax.swing.JTextArea();
        BS = new javax.swing.JComboBox<>();
        T1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        C1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        T2 = new javax.swing.JTextField();
        QN = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1282, 683));
        setMinimumSize(new java.awt.Dimension(1282, 683));
        setPreferredSize(new java.awt.Dimension(1696, 946));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DISCOUNT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 450, 40));

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT YOUR MEAL", "BREAKFAST", "LUNCH ", "DINNER", "BEVERAGES & SWEETS" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 450, 40));

        BF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT YOUR MEAL", "TEA", "MASALA TEA", "SPECIAL TEA(BISCUITS INCLUDED)", "COFFEE", "BISCUITS", "SOUTH INDIAN - COMBOO", "POHA JALEBI COMBO", "PARATHA COMBO", " ", " " }));
        BF.setVisible(false);
        BF.setFocusable(false);
        BF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFActionPerformed(evt);
            }
        });
        getContentPane().add(BF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 450, 30));

        DN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT YOUR MEAL", "PANEER COMBO", "CHINESE COMBO", "JAIN COMBO", "SOUTH INDIAN COMBO", "NORTH INDIAM COMBO", "RAJASTHANI COMBO", "CURD RICE" }));
        DN.setVisible(false);
        DN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNActionPerformed(evt);
            }
        });
        getContentPane().add(DN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 450, 30));

        LC.setVisible(false);
        LC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT YOUR MEAL", "CHOLE BHATURE COMBO", "STANDARD THALI", "JAIN THALI", "DAL BATI CHURMA", "VEG BIRYANI COMBO" }));
        LC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LCActionPerformed(evt);
            }
        });
        getContentPane().add(LC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 450, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GET YOUR MEALS HERE AT IRCTC ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 640, 60));

        TA1.setEditable(false);
        TA1.setColumns(20);
        TA1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TA1.setRows(10);
        jScrollPane1.setViewportView(TA1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 760, 380));

        BS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT YOUR MEAL", "GULAB JAMUN", "RASMALAI", "KESAR JALEBI", "RABRI", "MANGO SHAKE", "OREO SHAKE", "AMUL FLAVOURED MILK", "SPRITE", "AMUL LASSI", "VANILLA ICECREAM", "BISLERI MINERAL WATER" }));
        BS.setVisible(false);
        BS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSActionPerformed(evt);
            }
        });
        getContentPane().add(BS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 450, 30));

        T1.setEditable(false);
        getContentPane().add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 450, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SELECT YOU MEAL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 450, 40));

        C1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        C1.setForeground(new java.awt.Color(255, 255, 255));
        C1.setText("PAY ONLINE");
        C1.setToolTipText("PAY ONLINE & GET EXTRA 5% DISCOUNT");
        C1.setOpaque(false);
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        getContentPane().add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 520, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOTAL AMOUNT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 450, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("QUANTITY");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 450, 40));

        T2.setEditable(false);
        getContentPane().add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 450, 30));
        getContentPane().add(QN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 450, 40));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 450, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BOOKMEAL.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 400, 210));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" AT EXLUSIVE RATES..............");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 640, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BM2.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 360, 160));
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 190, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("<<back to home");
        jLabel11.setMaximumSize(new java.awt.Dimension(1282, 683));
        jLabel11.setPreferredSize(new java.awt.Dimension(1282, 683));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 150, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Railway-Wallpapers-009.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(1282, 683));
        jLabel7.setMinimumSize(new java.awt.Dimension(1282, 683));
        jLabel7.setPreferredSize(new java.awt.Dimension(1282, 683));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents
String item= null;

    private void LCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LCActionPerformed
    String i=null;
       
        
        
        
j=(int)LC.getSelectedIndex();
switch(j)
{
case 1:r=75;i="\n"+"\n" + "50gm OF CHOLE WITH 2 BHATURE"+ "\n"+"EXTRA BHATURE COSTS Rs.15 PER BHATURE";
break;
case 2:r=200;i="\n"+"\n" + "FRIED DAL"+ "\n"+"2 TAWA ROTI"+ "\n"+"SALAD"+ "\n"+"MANGO PICKLE"+ "\n"+"RAYTA"+ "\n"+"PAPAD"+ "\n"+"BUTTER PANEER" + "\n"+"SEASONAL VEGETABLE"+ "\n"+"FRIED RICE"+ "\n"+"GULAB JAMUN";
break;
case 3:r=250;i="\n"+"\n" + "FRIED DAL WITHOUT ONION TADKA"+ "\n"+"2 TAWA ROTI"+ "\n"+"SALAD"+ "\n"+"MANGO PICKLE"+ "\n"+"RAYTA"+ "\n"+"PAPAD"+ "\n"+"BUTTER PANEER WITHOUT ONION" + "\n"+"SEASONAL VEGETABLE WITHOUT ONION"+ "\n"+"JEERA RICE"+ "\n"+"GULAB JAMUN";
break;
case 4: r=300;i="\n"+"\n" + "4 Pcs OF BATI WITH DESI GHEE" + "\n" + "TADAKA DAL"+ "\n" + "SALAD"+ "\n" + "KAIREE CHUTNI"+ "\n" + "MANGO PICKLE"+ "\n" + "CHURMA MADE WITH DESI GHEE";
break;
case 5: r=150;i="\n"+"\n" + "250 gm OF VEG BIRYANI"+ "\n" + "RAYTA";
break;
}
final int lc=r;
TA1.setText("");
TA1.append("RATE:" + r + "\n" + "PRODUCT DESCRIPTION:"+ i);

// TODO add your handling code here:
    }//GEN-LAST:event_LCActionPerformed

    private void BFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFActionPerformed
String i=null;

k=(int)BF.getSelectedIndex();
switch(k)
{
case 1:r=10;i="\n"+"\n"+"1 CUP TEA";
break;
case 2:r=15;i="\n"+"\n"+"1 CUP TEA WITH NATURAL HERBS";
break;
case 3:r=20;i="\n"+"\n"+"1 CUP TEA WITH IMPORTED TEA BEANS";
break;
case 4: r=10;i="\n"+"\n"+"1 CUP COFFEE";
break;
case 5:r=10;i="\n"+"\n"+"MARIGOLD BISCUITS";
break;
case 6:r=40;i="\n"+"\n"+"2 Pc IDLI's WITH 50g OF SAMBHAR";
break;
case 7:r=30;i="\n"+"\n"+"SPECIAL MASALA POHA WITH SEV AND 1 Pc JALEBI";
break;
case 8: r=30;i="\n"+"\n"+"2 ALOO PARATHA WITH 1 PACKET OF TOMATO SAUCE";
break;
}
final int bf=r;
TA1.setText("");
TA1.append("RATE:" + r + "\n" + "PRODUCT DESCRIPTION:"+ i);
    }//GEN-LAST:event_BFActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
int l;
l=(int)c1.getSelectedIndex();
switch(l)
{
case 0: BF.setVisible(false);LC.setVisible(false);DN.setVisible(false);BS.setVisible(false);
break;
case 1: BF.setVisible(true);LC.setVisible(false);DN.setVisible(false);BS.setVisible(false);
break;
case 2: LC.setVisible(true);BF.setVisible(false);DN.setVisible(false);BS.setVisible(false);
break;
case 3: DN.setVisible(true);LC.setVisible(false);BF.setVisible(false);BS.setVisible(false);
break;
case 4: DN.setVisible(false);LC.setVisible(false);BF.setVisible(false);BS.setVisible(true);
break;
}        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void DNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNActionPerformed
String i=null;
      
m=(int)DN.getSelectedIndex();
switch(m)
{
case 1:r=200;i="\n"+"\n"+"2 TAWA ROTI"+"\n"+"MATAR PANEER"+"\n"+"SHAHI PANEER"+"\n"+"FRIED RICE"+"\n"+"PAPAD"+"\n"+"MANGO PICKLE"+"\n"+"SALAD";
break;
case 2:r=150;i="\n"+"\n"+"NOODLES"+"\n"+"CHAUMIN"+"\n"+"HOT SOUP"+"\n"+"SPRING ROLLS";
break;
case 3:r=200;i="\n"+"\n" + "FRIED DAL WITHOUT ONION TADKA"+ "\n"+"2 TAWA ROTI"+ "\n"+"SALAD"+ "\n"+"MANGO PICLE"+ "\n"+"RAYTA"+ "\n"+"PAPAD"+ "\n"+"BUTTER PANEER WITHOUT ONION" + "\n"+"SEASONAL VEGETABLE WITHOUT ONION"+ "\n"+"JEERA RICE"+ "\n"+"GULAB JAMUN";
break;
case 4: r=150;i="\n"+"\n"+"3 Pc IDLI"+"\n"+"SAMBHAR"+"\n"+"VADA"+"\n"+"MASALA DOSA"+"\n"+"UTPAM"+"\n"+"COCONUT CHUTNEY";
break;
case 5: r=180;i="\n"+"\n"+"2 Pcs TANDOORI ROTI"+"\n"+"SARSO DA SAAG"+"\n"+"SALAD"+"\n"+"PAPAD"+"\n"+"RAYTA"+"\n"+"FRIED RICE"+"\n"+"FRIED DAAL"+"\n"+"MANGO PICKLE";
break;
case 6: r=200;i="\n"+"\n"+"BESAN GATTE"+"\n"+"1 CUP OF CURD"+"\n"+"BASMATI RICE"+"\n"+"1 GLASS OF CHAAJH"+"\n"+"2 Pcs OF GHEVAR";
break;
case 7: r=70;i="\n"+"\n"+"BASMATI RICE"+"\n"+"AMUL CURD";
break;
}
final int dn=r;
TA1.setText("");
TA1.append("RATE:" + r + "\n" + "PRODUCT DESCRIPTION:"+ i);// TODO add your handling code here:
    }//GEN-LAST:event_DNActionPerformed


    private void BSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSActionPerformed
String i=null;
       
n=(int)BS.getSelectedIndex();
switch(n)
{
case 1:r=30;i="\n"+"\n"+"2 Pcs OF GULAB JAMUN";
break;
case 2:r=40;i="\n"+"\n"+"2 Pcs OF RAS MALAI";
break;
case 3:r=50;i="\n"+"\n"+"3 Pcs OF KESAR JALEBI";
break;
case 4: r=65;i="\n"+"\n"+"250 gm  OF RABRI";
break;
case 5: r=50;i="\n"+"\n"+"1 GLASS OF MANGO SHAKE";
break;
case 6: r=80;i="\n"+"\n"+"1 GLASS OF OREO SHAKE";
break;
case 7: r=30;i="\n"+"\n"+"250 mL OF FLAVOURED MILK";
break;
case 8: r=30;i="\n"+"\n"+"500 mL OF SPRITE BOTTLE";
break;
case 9: r=20;i="\n"+"\n"+"250 mL OF AMUL LASSI";
break;
case 10: r=20;i="\n"+"\n"+"1 CUP OF VANILLA FLAVOURED ICE CREAM";
break;
case 11: r=30;i="\n"+"\n"+"1 L OF PACKED MINERAL WATER";
break;
}
final int bs=r;
TA1.setText("");
TA1.append("RATE:" + r + "\n" + "PRODUCT DESCRIPTION:"+ i);        // TODO add your handling code here:
    }//GEN-LAST:event_BSActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a,e,c=0,rt=0,d;
        String un1;
a=Integer.parseInt(QN.getText());
un1=L2.getText();
c=a*r;
if(C1.isSelected())
{
d=(c*5)/100;
}
else
{
d=0;
}

e=c-d;
T1.setText(""+d);
T2.setText(""+e);
TA1.setText("");
TA1.append("                                                          TAX INVOICE                                                          "+"\n"+"\n"+"\n"+"YOUR TOTAL AMOUNT IS:   "+ e+"\n"+"\n"+"\n"+"THANKS FOR HAVING TRANSACTION WITH IRCTC");
System.out.println(bf);
System.out.println(lc);
System.out.println(dn);
System.out.println(bs);


item=(String) c1.getSelectedItem();
          try{
           // Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
       // Connection con = DriverManager.getConnection("jdbc:odbc:ins");
           Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/irctc?zeroDateTimeBehavior=convertToNull","root","123456");
            Statement stmt=con.createStatement();
            String sql="Insert into book_meals1 values('"+un1+"','"+item+"',"+e+")";
               stmt.executeUpdate(sql);
           JOptionPane.showMessageDialog(null,"YOUR ORDER IS BOOKED THANK YOU FOR HAVING TRANSACTION");
          
          }
       catch(Exception ex)
       {
       JOptionPane.showMessageDialog(null,ex.getMessage());
       }
int pm=0;
pm=e;
PAYMENT RR=new PAYMENT(pm,L2.getText());
     RR.setVisible(true);this.dispose();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new HOME(L2.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BOOK_MEALS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BOOK_MEALS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BOOK_MEALS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BOOK_MEALS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BOOK_MEALS(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BF;
    private javax.swing.JComboBox<String> BS;
    private javax.swing.JCheckBox C1;
    private javax.swing.JComboBox<String> DN;
    private javax.swing.JLabel L2;
    private javax.swing.JComboBox<String> LC;
    private javax.swing.JTextField QN;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextArea TA1;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
