  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author SAMYAK & ATISHAY
 */
public class CREATE_ACCOUNT extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public CREATE_ACCOUNT() {
        initComponents();
            UIManager.put("OptionPane.messageFont", new Font("TIMES NEW ROMAN", Font.BOLD, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        b1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        e1 = new javax.swing.JPasswordField();
        s1 = new javax.swing.JTextField();
        n1 = new javax.swing.JTextField();
        pw1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        PASSWORD = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        r2 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        ct1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cn1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        oc1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ph1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        rg1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pw2 = new javax.swing.JPasswordField();
        mon = new javax.swing.JComboBox();
        yer = new javax.swing.JComboBox();
        day = new javax.swing.JComboBox();
        un1 = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(getBackground());
        setMaximumSize(new java.awt.Dimension(1282, 683));
        setMinimumSize(new java.awt.Dimension(1282, 683));
        setPreferredSize(new java.awt.Dimension(1282, 683));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USERNAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 40));

        e1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        e1.setEchoChar(e1.getFocusAccelerator());
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 880, 30));

        s1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        getContentPane().add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 880, 30));

        n1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });
        getContentPane().add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 880, -1));

        pw1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        pw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw1ActionPerformed(evt);
            }
        });
        getContentPane().add(pw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 880, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CITY");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 240, 40));

        PASSWORD.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        PASSWORD.setForeground(new java.awt.Color(255, 255, 255));
        PASSWORD.setText("PASSWORD");
        getContentPane().add(PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 290, 60));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("STATE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 290, 60));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NAME");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 270, 40));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 290, 90));

        b1.add(r2);
        r2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.setText("FEMALE");
        r2.setOpaque(false);
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, 300, 30));

        b1.add(r1);
        r1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.setText("MALE");
        r1.setOpaque(false);
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 270, 30));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("GENDER");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 290, 80));

        ct1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        ct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct1ActionPerformed(evt);
            }
        });
        getContentPane().add(ct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 880, 30));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DATE OF BIRTH");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 290, 50));

        cn1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cn1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIA", "USA", "AUSTRALIA", "PAKISTAN", "BANGLADESH", "NEPAL", "EGYPT", "GERMANY", "ENGLAND", "WEST INDIES", "SRI LANKA", "SWITZERLAND", "IRAN", "IRAQ", "IRELAND", "FRANCE", "CHINA", "FIJI", "ITALY", "BRAZIL", "POLAND", "BELGIUM", "RUSSIA" }));
        cn1.setToolTipText("");
        cn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cn1ActionPerformed(evt);
            }
        });
        getContentPane().add(cn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 880, 30));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("OCCUPATION");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 290, 40));

        oc1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        oc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT OCUPATION", "GOVERNMENT", "PUBLIC", "PRIVATE", "SELF EMPLOYED", "PROFESSIONAL", "STUDENT", "OTHER" }));
        oc1.setToolTipText("");
        getContentPane().add(oc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 880, 30));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PHONE NUMBER");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 290, 70));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NATIONALITY");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 290, 50));

        ph1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        ph1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ph1ActionPerformed(evt);
            }
        });
        getContentPane().add(ph1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, 880, 30));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("EMAIL");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 260, 40));

        c1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setText("I ACCEPT THE TERMS AND CONDITIONS.");
        c1.setOpaque(false);
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 510, 40));

        rg1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        rg1.setForeground(new java.awt.Color(255, 255, 255));
        rg1.setText("REGISTER");
        rg1.setEnabled(false);
        rg1.setOpaque(false);
        rg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rg1ActionPerformed(evt);
            }
        });
        getContentPane().add(rg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 550, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/irt2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 130));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IRCTC MEMBERSHIP REGISTRATION COLUMN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 1660, 90));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1900, -1));

        pw2.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        pw2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw2ActionPerformed(evt);
            }
        });
        getContentPane().add(pw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 880, 30));

        mon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MONTH", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monActionPerformed(evt);
            }
        });
        getContentPane().add(mon, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 120, 30));

        yer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        yer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YEAR", "1980", "1981", "1882", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", " ", " " }));
        getContentPane().add(yer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 90, 30));

        day.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DATE", "1", "2", "3", "4", "5", "6", "7", "8", "9", "1", "1", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 90, 30));

        un1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        un1.setEchoChar(un1.getFocusAccelerator());
        getContentPane().add(un1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 880, 40));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("<<BACK TO LOGIN");
        jLabel17.setAlignmentX(0.5F);
        jLabel17.setAutoscrolls(true);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 200, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/559128.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e1ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1ActionPerformed

    private void pw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pw1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        {
        }    }//GEN-LAST:event_r2ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
 String ge;
        
       
 {
        }    }//GEN-LAST:event_r1ActionPerformed

    private void ct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct1ActionPerformed

    private void cn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cn1ActionPerformed

    private void ph1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ph1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ph1ActionPerformed

    private void rg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rg1ActionPerformed
 String un,ct,pw=null,n,s,e,ge,oc,cn,cpw=null;

n=n1.getText();
        un=new String(un1.getPassword());

        ct=ct1.getText();
 
           pw=new String(pw1.getPassword());
           cpw=new String(pw2.getPassword());
         
         if (r1.isSelected())
        {
        ge="male";
        }
     else
        {
        ge="female";
        }
         
         String dy=(String)day.getSelectedItem();
         String mn=(String)mon.getSelectedItem();
         String yr=(String)yer.getSelectedItem();
         String dob=(String)(yr+"/"+mn+"/"+dy);
         
        oc=  (String)oc1.getSelectedItem();
         
        cn=  (String) cn1.getSelectedItem();
        s=s1.getText();
        e=new String(e1.getPassword());
        int c=0;
        

    
 if(cpw.equals(pw)){
       
        
       try{
           // Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
       // Connection con = DriverManager.getConnection("jdbc:odbc:ins");
           Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/irctc?zeroDateTimeBehavior=convertToNull","root","123456");
            Statement stmt=con.createStatement();
            String sql="Insert into register values('"+n+"','"+un+"','"+ct+"','"+pw+"','"+ge+"','"+dob+"','"+oc+"','"+cn+"','"+s+"','"+e+"')";
           
                 
        stmt.executeUpdate(sql);
            }
      
       catch(Exception ex)
       {
       JOptionPane.showMessageDialog(null,ex.getMessage());
       }
      JOptionPane.showMessageDialog(null,"Member Registered Successfully...");}
         else{
             JOptionPane.showMessageDialog(null,"CONFIRM PASSWORD MUST BE EQUAL TO PASSWORD");
       }
 
    this.dispose();
     LOGIN l=new LOGIN();
     l.setVisible(true);
     
    }//GEN-LAST:event_rg1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
if (c1.isSelected())
        {
        rg1.setEnabled(true);
        }
        
        else
        {
        rg1.setEnabled(false);
        }       
    }//GEN-LAST:event_c1ActionPerformed

    private void pw2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pw2ActionPerformed

    private void monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        new LOGIN().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jLabel17MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CREATE_ACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CREATE_ACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CREATE_ACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CREATE_ACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CREATE_ACCOUNT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PASSWORD;
    private javax.swing.ButtonGroup b1;
    private javax.swing.JCheckBox c1;
    private javax.swing.JComboBox<String> cn1;
    private javax.swing.JTextField ct1;
    private javax.swing.JComboBox day;
    private javax.swing.JPasswordField e1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox mon;
    private javax.swing.JTextField n1;
    private javax.swing.JComboBox<String> oc1;
    private javax.swing.JTextField ph1;
    private javax.swing.JPasswordField pw1;
    private javax.swing.JPasswordField pw2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JButton rg1;
    private javax.swing.JTextField s1;
    private javax.swing.JPasswordField un1;
    private javax.swing.JComboBox yer;
    // End of variables declaration//GEN-END:variables
}
