


import java.sql.*;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAMYAK & ATISHAY
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
           @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UN1 = new javax.swing.JPasswordField();
        PW1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        load = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(991, 704));
        setMinimumSize(new java.awt.Dimension(991, 704));
        setPreferredSize(new java.awt.Dimension(991, 704));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 330, 82));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 290, 80));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 290, 60));

        UN1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        UN1.setEchoChar(UN1.getFocusAccelerator());
        UN1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UN1FocusGained(evt);
            }
        });
        UN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UN1ActionPerformed(evt);
            }
        });
        getContentPane().add(UN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 410, 60));

        PW1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        PW1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PW1ActionPerformed(evt);
            }
        });
        getContentPane().add(PW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 410, 60));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("LOGIN TO NEXT GENERATION TICKETING SYSTEM");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 710, 110));

        jSeparator1.setOpaque(true);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 198, 950, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 22, 950, 10));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/irt2.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 150, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("IF NO ACCOUNT CLICK HERE TO CREATE NEW NEW ACCOUNT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, 450, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setText("NEW ACCOUNT");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, 180, 20));

        load.setVisible(false);
        getContentPane().add(load, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 320, 320));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/703812.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int h;String a;
    private void UN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UN1ActionPerformed
String un;
        un=new String(UN1.getPassword());    }//GEN-LAST:event_UN1ActionPerformed

    private void PW1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PW1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PW1ActionPerformed

    private void UN1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UN1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_UN1FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String un,pw,m=null;
        un=new String(UN1.getPassword());
        pw=new String(PW1.getPassword());
        
    
     
        try
        {
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/irctc?zeroDateTimeBehavior=convertToNull","root","123456");
            Statement stmt=con.createStatement();
            String sql="select pw from register where un='"+un+"'";
            
           ResultSet rs= stmt.executeQuery(sql);
            while (rs.next()) {
           
             a= rs.getString("pw");
               
               }
         if(rs.next())
           {
          new HOME(un).setVisible(true);
             this.dispose();
        }
           if(a.equals(pw))
           {
           
           
             new HOME(un).setVisible(true);
             this.dispose();
           }
        else
        {
        JOptionPane.showMessageDialog(null,"PLEASE ENTER VALID PASSWORD");
        }
     
        }
        
        
        
        
catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,ex.getMessage());
        }
            if(un.equals("admin") && pw.equals("admin1234"))
           {
            JOptionPane.showMessageDialog(null,"WELCOME ADMIN...............");
           
             new ADMIN().setVisible(true);
             this.dispose();
           }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
     
        
       
        CREATE_ACCOUNT CREATE_ACCOUNT = new CREATE_ACCOUNT();
        CREATE_ACCOUNT.setVisible(true);
       
       this.dispose();
       
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PW1;
    private javax.swing.JPasswordField UN1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel load;
    // End of variables declaration//GEN-END:variables
}
