
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAMYAK & ATISHAY
 */
public class MY_TRANSACTIONS extends javax.swing.JFrame {

    /**
     * Creates new form MY_TRANSACTIONS
     */
    public MY_TRANSACTIONS(String un) {
        initComponents();
        L2.setText(un);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        TB5 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TB3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TB4 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        TB1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        BTM = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1282, 683));
        setMinimumSize(new java.awt.Dimension(1282, 683));
        setPreferredSize(new java.awt.Dimension(1282, 683));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("SHOW TRANSACTIONS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 360, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1060, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW YOUR TRANSACTIONS.......");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 850, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MY TRANSACTION.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(1282, 683));
        jLabel2.setMinimumSize(new java.awt.Dimension(1282, 683));
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1282, 683));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 230, 230));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1060, 20));

        TB5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RIDE_TYPE", "NO.OF TICKETS", "AMOUNT"
            }
        ));
        jScrollPane2.setViewportView(TB5);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 550, 410, 110));

        TB3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RIDE_TYPE", "NO.OF TICKETS", "AMOUNT"
            }
        ));
        jScrollPane3.setViewportView(TB3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 410, 110));

        TB4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RIDE_TYPE", "NO.OF TICKETS", "AMOUNT"
            }
        ));
        jScrollPane4.setViewportView(TB4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 410, 110));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("LUXURY TRAINS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 110, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("BHARAT DARSHAN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 520, 130, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("MEALS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 110, 30));

        TB2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ROOM", "AMOUNT"
            }
        ));
        jScrollPane1.setViewportView(TB2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 260, 180));

        TB1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "TOTAL_AMT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(TB1);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 170));

        BTM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PNR", "DOJ", "NO.OF PASSENGERS", "SRC", "DST", "FARE", "TRAIN NO. & NAME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BTM.setColumnSelectionAllowed(true);
        jScrollPane6.setViewportView(BTM);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 980, 240));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setText("TOURIST TRAIN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 110, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel7.setText("RETIRING ROOM");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 110, 30));
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 170, 20));

        jLabel11.setForeground(new java.awt.Color(153, 255, 255));
        jLabel11.setText("<<back to home");
        jLabel11.setMaximumSize(new java.awt.Dimension(1282, 683));
        jLabel11.setPreferredSize(new java.awt.Dimension(1282, 683));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ts.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setMaximumSize(new java.awt.Dimension(1282, 683));
        jLabel8.setMinimumSize(new java.awt.Dimension(1282, 683));
        jLabel8.setPreferredSize(new java.awt.Dimension(1282, 683));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          //for showing the record
          DefaultTableModel mm=(DefaultTableModel) TB1.getModel();
        

           TB1.setVisible(true);
           try
        {
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/irctc?zeroDateTimeBehavior=convertToNull","root","123456");
            Statement stmt=con.createStatement();
            String sql="select * from book_meals1 where username1='"+ L2.getText()+"'";
            System.out.println(sql);
           ResultSet rs= stmt.executeQuery(sql);
           while(rs.next())
           {
             
               String m=rs.getString("item");
               int tm = rs.getInt("total_amount");
                mm.addRow(new Object[]{m,tm});

           }
           
          
        }catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,ex.getMessage());
        }
           
      DefaultTableModel mn=(DefaultTableModel) TB2.getModel();
        

           TB1.setVisible(true);
           try
        {
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/irctc?zeroDateTimeBehavior=convertToNull","root","123456");
            Statement stmt=con.createStatement();
            String sql="select * from retiring_room where username2='"+ L2.getText()+"'";
            System.out.println(sql);
           ResultSet rs= stmt.executeQuery(sql);
           while(rs.next())
           {
             
               String m=rs.getString("room");
               int tm = rs.getInt("amount");
                mn.addRow(new Object[]{m,tm});

           }
           
          
        }catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,ex.getMessage());
        }
      DefaultTableModel mO=(DefaultTableModel) TB3.getModel();
        

           TB1.setVisible(true);
           try
        {
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/irctc?zeroDateTimeBehavior=convertToNull","root","123456");
            Statement stmt=con.createStatement();
            String sql="select * from T_T1 where username3='"+ L2.getText()+"'";
            System.out.println(sql);
           ResultSet rs= stmt.executeQuery(sql);
           while(rs.next())
           {
             
               String m=rs.getString("ride_type");
               int tn = rs.getInt("no_of_tickets");
               int tm = rs.getInt("total_amount");
                mO.addRow(new Object[]{m,tn,tm});

           }
           
          
        }catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,ex.getMessage());
        }
     DefaultTableModel mp=(DefaultTableModel) TB4.getModel();
        

           TB1.setVisible(true);
           try
        {
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/irctc?zeroDateTimeBehavior=convertToNull","root","123456");
            Statement stmt=con.createStatement();
            String sql="select * from T_T2 where username4='"+ L2.getText()+"'";
            System.out.println(sql);
           ResultSet rs= stmt.executeQuery(sql);
           while(rs.next())
           {
             
               String m=rs.getString("ride_type");
               int tn = rs.getInt("no_of_tickets");
               int tm = rs.getInt("total_amount");
                mp.addRow(new Object[]{m,tn,tm});

           }
           
          
        }catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,ex.getMessage());
        }
     DefaultTableModel mq=(DefaultTableModel) TB5.getModel();
        

           TB1.setVisible(true);
           try
        {
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/irctc?zeroDateTimeBehavior=convertToNull","root","123456");
            Statement stmt=con.createStatement();
            String sql="select * from T_T3 where username5='"+ L2.getText()+"'";
            System.out.println(sql);
           ResultSet rs= stmt.executeQuery(sql);
           while(rs.next())
           {
             
               String m=rs.getString("ride_type");
               int tn = rs.getInt("no_of_tickets");
               int tm = rs.getInt("total_amount");
                mq.addRow(new Object[]{m,tn,tm});

           }
           
          
        }catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,ex.getMessage());
        }
     DefaultTableModel mb=(DefaultTableModel) BTM.getModel();
        

           TB1.setVisible(true);
           try
        {
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/irctc?zeroDateTimeBehavior=convertToNull","root","123456");
            Statement stmt=con.createStatement();
            String sql="select PNR,DOJ,NOP,SRC,DST,FARE,TRAIN from BOOK_TICKET where username='"+ L2.getText()+"'";
            System.out.println(sql);
           ResultSet rs= stmt.executeQuery(sql);
           while(rs.next())
           {
             int pnr = rs.getInt("PNR");
             String src=rs.getString("SRC");
             String dst=rs.getString("DST");
               String doj=rs.getString("DOJ");
               int np = rs.getInt("NOP");
               int fr = rs.getInt("FARE");
               String train =rs.getString("TRAIN");
                mb.addRow(new Object[]{pnr,doj,np,src,dst,fr,train});

           }
           
          
        }catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,ex.getMessage());
        }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new HOME(L2.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MY_TRANSACTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MY_TRANSACTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MY_TRANSACTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MY_TRANSACTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MY_TRANSACTIONS(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BTM;
    private javax.swing.JLabel L2;
    private javax.swing.JTable TB1;
    private javax.swing.JTable TB2;
    private javax.swing.JTable TB3;
    private javax.swing.JTable TB4;
    private javax.swing.JTable TB5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
