
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAMYAK & ATISHAY
 */
public class T_T1 extends javax.swing.JFrame {

    /**
     * Creates new form T_T1
     */
    public T_T1(String un) {
        initComponents();
        L2.setText(un);
        
        
    }

   
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        DT = new javax.swing.JLabel();
        MT = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DTT = new javax.swing.JTextArea();
        NT = new javax.swing.JLabel();
        ST = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        STT = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        MTT = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        NTT = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        R1 = new javax.swing.JRadioButton();
        R2 = new javax.swing.JRadioButton();
        R3 = new javax.swing.JRadioButton();
        R4 = new javax.swing.JRadioButton();
        L2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1282, 683));
        setMinimumSize(new java.awt.Dimension(1282, 683));
        setPreferredSize(new java.awt.Dimension(1282, 683));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TT1.2.jpg"))); // NOI18N
        DT.setText("jLabel1");
        DT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DTMouseExited(evt);
            }
        });
        getContentPane().add(DT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 240, 180));

        MT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TT1.4.jpg"))); // NOI18N
        MT.setText("jLabel1");
        MT.setOpaque(true);
        MT.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MTMouseDragged(evt);
            }
        });
        MT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MTMouseExited(evt);
            }
        });
        getContentPane().add(MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 260, 220));

        jScrollPane1.setVisible(false);

        DTT.setVisible(false);
        DTT.setColumns(20);
        DTT.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DTT.setRows(5);
        DTT.setText("The Darjeeling Himalayan Railway, with the\n nickname \"the Toy Train,\" is a 610mm (2 ft)\n narrow-gauge railway that links the 88 km \n(55 mi)between Siliguri and Darjeeling.\n\ncharges-Rs250/person");
        jScrollPane1.setViewportView(DTT);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 480, 240));

        NT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TT1.1.jpg"))); // NOI18N
        NT.setText("jLabel1");
        NT.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                NTMouseDragged(evt);
            }
        });
        NT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NTMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NTMouseReleased(evt);
            }
        });
        getContentPane().add(NT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 230, 180));

        ST.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tt1.3.jpg"))); // NOI18N
        ST.setText("jLabel1");
        ST.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                STMouseDragged(evt);
            }
        });
        ST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                STMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                STMouseExited(evt);
            }
        });
        getContentPane().add(ST, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 240, 180));

        jScrollPane3.setVisible(false);

        STT.setVisible(false);
        STT.setColumns(20);
        STT.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        STT.setRows(5);
        STT.setText("The Kalka–Shimla Railway\n runs between Kalka and \nShimla. The railway is 95.66\n km (59.44 mi) long, and its\n gauge is narrow 2 ft 6 in \n(762 mm).\ncharges-Rs200/person\n");
        jScrollPane3.setViewportView(STT);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 430, 240));

        jScrollPane4.setVisible(false);

        MTT.setVisible(false);
        MTT.setColumns(20);
        MTT.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        MTT.setRows(5);
        MTT.setText("The Matheran Hill Railway\nand goes for 21 km (13 mi)\n between Neral and Matheran,\n in the Western Ghats.\n\ncharges-Rs 250/person");
        jScrollPane4.setViewportView(MTT);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 430, 240));

        jScrollPane5.setVisible(false);

        NTT.setVisible(false);
        NTT.setEditable(false);
        NTT.setColumns(20);
        NTT.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NTT.setRows(5);
        NTT.setText("The Nilgiri Mountain Railway is a 46 km \n(29 mi) metre gauge single-line railway. It \nis 46 km (29 mi) long and connects the town\n of Mettupalayam with the hill station of\n Udagamandalam (Ootacamund). \n\ncharges-Rs250/person;");
        NTT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane5.setViewportView(NTT);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 470, 240));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TOTAL PAYABLE AMOUNT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 290, 40));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 340, 290, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NO OF TICKETS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 260, 40));

        t2.setEditable(false);
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 430, 170, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CLICK BELOW TO CONFIRM");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 300, 40));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, 300, 100));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 202, 1410, 0));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TOURIST TRAINS......");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 620, 110));

        buttonGroup1.add(R1);
        R1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        R1.setForeground(new java.awt.Color(255, 255, 255));
        R1.setText("NILGIRI TOY TRAIN");
        R1.setOpaque(false);
        getContentPane().add(R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, 30));

        buttonGroup1.add(R2);
        R2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        R2.setForeground(new java.awt.Color(255, 255, 255));
        R2.setText("DARJELLING TOY TRAIN");
        R2.setOpaque(false);
        getContentPane().add(R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 210, -1));

        buttonGroup1.add(R3);
        R3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        R3.setForeground(new java.awt.Color(255, 255, 255));
        R3.setText("SHIMLA TOY TRAIN");
        R3.setOpaque(false);
        R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3ActionPerformed(evt);
            }
        });
        getContentPane().add(R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        buttonGroup1.add(R4);
        R4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        R4.setForeground(new java.awt.Color(255, 255, 255));
        R4.setText("MAHASARN TOY TRAIN");
        R4.setOpaque(false);
        R4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R4ActionPerformed(evt);
            }
        });
        getContentPane().add(R4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 230, 40));

        L2.setBackground(new java.awt.Color(255, 255, 255));
        L2.setOpaque(true);
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 190, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USERNAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 120, 30));

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("<<back to tourist trains");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 150, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 500, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 252, 10, 430));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tt1w.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1280, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MTMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MTMouseDragged
        
    }//GEN-LAST:event_MTMouseDragged

    private void STMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_STMouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int nt ,ta,d=0;String name=null;
        nt=Integer.parseInt(t1.getText());
        if (R1.isSelected())
        { d=200;name="Nilgiri Mountain Railway";
                }
         if (R2.isSelected())
        { d=250;name="Kalka–Shimla Railway";
                }
          if (R3.isSelected())
        { d=250;name="Darjeeling Himalayan Railway,";
                }
           if (R4.isSelected())
        { d=200;name="Matheran railway";
                }
        ta=d*nt;
        t2.setText(""+ta);
         
             try{
           // Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
       // Connection con = DriverManager.getConnection("jdbc:odbc:ins");
           Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/irctc?zeroDateTimeBehavior=convertToNull","root","123456");
            Statement stmt=con.createStatement();
            String sql="Insert into T_T1 values('"+L2.getText()+"','"+name+"','"+nt+"',"+ta+")";
           stmt.executeUpdate(sql);
          }
       catch(Exception ex)
       {
       JOptionPane.showMessageDialog(null,ex.getMessage());
       }
int pm=0;
pm=ta;
PAYMENT RR=new PAYMENT(pm, L2.getText());
     RR.setVisible(true);this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NTMouseReleased
       
    }//GEN-LAST:event_NTMouseReleased

    private void NTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NTMousePressed
         
    }//GEN-LAST:event_NTMousePressed

    private void NTMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NTMouseDragged
              // TODO add your handling code here:
    }//GEN-LAST:event_NTMouseDragged

    private void NTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NTMouseExited
         NTT.setVisible(false);
         jScrollPane5.setVisible(false);
         NT.setVisible(true);
    }//GEN-LAST:event_NTMouseExited

    private void NTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NTMouseEntered
         NTT.setVisible(true);
           jScrollPane5.setVisible(true);
          NT.setVisible(false);
    }//GEN-LAST:event_NTMouseEntered

    private void DTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DTMouseEntered
      DTT.setVisible(true);
      jScrollPane1.setVisible(true);
          DT.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_DTMouseEntered

    private void DTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DTMouseExited
        // TODO add your handling code here:
         DTT.setVisible(false);
         jScrollPane1.setVisible(false);
         DT.setVisible(true);
    }//GEN-LAST:event_DTMouseExited

    private void STMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STMouseEntered
         STT.setVisible(true);
         jScrollPane3.setVisible(true);
          ST.setVisible(false);
    }//GEN-LAST:event_STMouseEntered

    private void STMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STMouseExited
          STT.setVisible(false);
          jScrollPane3.setVisible(false);
         ST.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_STMouseExited

    private void MTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MTMouseEntered
        // TODO add your handling code here:
        MTT.setVisible(true);
        jScrollPane4.setVisible(true);
          MT.setVisible(false);
    }//GEN-LAST:event_MTMouseEntered

    private void MTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MTMouseExited
        // TODO add your handling code here:
           MTT.setVisible(false);
           jScrollPane4.setVisible(false);
         MT.setVisible(true);
    }//GEN-LAST:event_MTMouseExited

    private void R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R3ActionPerformed

    private void R4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R4ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
            new TOURIST_TRAIN(L2.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T_T1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T_T1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T_T1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T_T1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T_T1(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DT;
    private javax.swing.JTextArea DTT;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel MT;
    private javax.swing.JTextArea MTT;
    private javax.swing.JLabel NT;
    private javax.swing.JTextArea NTT;
    private javax.swing.JRadioButton R1;
    private javax.swing.JRadioButton R2;
    private javax.swing.JRadioButton R3;
    private javax.swing.JRadioButton R4;
    private javax.swing.JLabel ST;
    private javax.swing.JTextArea STT;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
