
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAMYAK & ATISHAY
 */
public class T_T2 extends javax.swing.JFrame {
    /**
     * Creates new form T_T2
     */
    public T_T2(String un) {
        initComponents();
           L2.setText(un);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ST = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        TF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        INFO = new javax.swing.JTextArea();
        NT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        FPP = new javax.swing.JTextField();
        P2 = new javax.swing.JLabel();
        P3 = new javax.swing.JLabel();
        P4 = new javax.swing.JLabel();
        P1 = new javax.swing.JLabel();
        P0 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1282, 683));
        setMinimumSize(new java.awt.Dimension(1282, 683));
        setPreferredSize(new java.awt.Dimension(1282, 683));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 3, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pride of Indian Railways-Luxury Trains");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 1080, 80));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FAIR (ALL TAX INCLUDED)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 360, 60));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("FAIR PER PERSON");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 230, 50));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("NO.OF TICKETS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 290, 60));

        ST.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ST.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT YOUR TRAIN", "MAHARAJA EXPRESS", "ROYAL RAJASTHAN EXPRESS", "GOLDEN CHARIOT EXPRSS", "DECCAN ODYSSEY EXPRSS" }));
        ST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STActionPerformed(evt);
            }
        });
        getContentPane().add(ST, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 500, 40));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton1.setText("CONTINUE YOUR AMAZING TRAIN JOURNEY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 520, 70));

        TF.setEditable(false);
        TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFActionPerformed(evt);
            }
        });
        getContentPane().add(TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 500, 50));

        INFO.setEditable(false);
        INFO.setColumns(20);
        INFO.setFont(new java.awt.Font("Sitka Small", 1, 21)); // NOI18N
        INFO.setRows(5);
        jScrollPane1.setViewportView(INFO);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 1260, 110));

        NT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NTActionPerformed(evt);
            }
        });
        getContentPane().add(NT, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 500, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("SELECT YOUR TRAIN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 280, 50));
        getContentPane().add(FPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, 260, 40));

        P2.setVisible(false);
        P2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palace on wheels.jpg"))); // NOI18N
        P2.setText("jLabel3");
        getContentPane().add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 660, 420));

        P3.setVisible(false);
        P3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/golden-chariot.jpg"))); // NOI18N
        P3.setText("jLabel3");
        getContentPane().add(P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 660, 400));

        P4.setVisible(false);
        P4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deccan odyssey.jpg"))); // NOI18N
        P4.setText("jLabel3");
        getContentPane().add(P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 660, 440));

        P1.setVisible(false);
        P1.setFont(null);
        P1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Maharajas-Express-Train.jpg"))); // NOI18N
        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 680, 450));

        P0.setVisible(true);
        P0.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        P0.setText("SELECT YOUR TRAIN");
        getContentPane().add(P0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 700, 450));

        L2.setBackground(new java.awt.Color(255, 255, 255));
        L2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        L2.setOpaque(true);
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 190, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("USERNAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 180, 30));

        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("<<back to tourist trains");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, 150, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lt1w.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setMaximumSize(new java.awt.Dimension(1282, 683));
        jLabel9.setMinimumSize(new java.awt.Dimension(1282, 683));
        jLabel9.setPreferredSize(new java.awt.Dimension(1282, 683));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 int f=0;
    
    private void STActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STActionPerformed
    int train ;String i=null;
    
    train=(int) ST.getSelectedIndex();
    switch (train)
    {
              case 0:
    P0.setVisible(true);
    P3.setVisible(false);P2.setVisible(false);P4.setVisible(false);
   P1.setVisible(false);
    
    f=0;
    break;
       
        case 1:
    P1.setVisible(true);
    P3.setVisible(false);P2.setVisible(false);P4.setVisible(false); P0.setVisible(false);
    i= "MAHARAJA EXPRESS-PRIDE OF INDIA"+ "\n"+"The Maharajas' Express is a luxury tourist train owned and operated by Indian Railway Catering and Tourism Corporation."+"\n"+ "It runs on 4 circuits covering more than 12 destinations across North-West and Central India, mainly centered on Rajasthan between the months of October and April."+"+\n"+"The Maharajas' Express was voted The World's Leading Luxury Train Seven times in a row at The World Travel Awards in 2012, 2013, 2014,2015, 2016, 2017 and 2018.";
    f=100000;
    break;
    
    case 2:
     P2.setVisible(true);
    P1.setVisible(false);P3.setVisible(false);P4.setVisible(false); P0.setVisible(false);
    
    i= "PALACE ON WHEELS"+ "\n"+"The Palace on Wheels is a luxury tourist train. It was launched "+"\n"+"by the Indian Railways in association with Rajasthan Tourism Development Corporation to promote tourism in Rajasthan.[1].";
     f=80000;
    break;
     case 3:
  P3.setVisible(true);
  P4.setVisible(false);P2.setVisible(false);P1.setVisible(false); P0.setVisible(false);
    
    i= "GOLDEN CHARIOT"+ "\n"+"The Golden Chariot is a luxury tourist train that connects the important tourist spots in the"+"\n"+" Indian states of Karnataka, Goa, Kerala & Tamil Nadu as well as Pondicherry, depending on the"+"\n"+" selected itinerary. It is named after the Stone Chariot in the Vitthala Temple at Hampi.";
    f=70000;
    break;
    case 4:
    P4.setVisible(true);
    P1.setVisible(false);P3.setVisible(false);P2.setVisible(false); P0.setVisible(false);
    i= "DECCAN ODYSSEY"+ "\n"+"The Deccan Odyssey is a special luxury train based on the model of Palace on Wheels to"+"\n"+" boost tourism on the Maharashtra route of the Indian Railways. It is a venture"+"\n"+" of the Maharashtra Government and the Ministry of Railways, Government of India. ";
    f=60000;
    break;
    }
    FPP.setText(""+f);
   INFO.setText(""+i);
//MAHARAJA EXPRESS

//The Maharajas' Express was voted "The World's Leading Luxury Train" Seven times in a row at The World Travel Awards in 2012, 2013, 2014,2015, 2016, 2017 and 2018.
    }//GEN-LAST:event_STActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int not,total=0;
         not=Integer.parseInt(NT.getText());
         total=not*f;
         TF.setText(""+total);
         
         String tn=(String)ST.getSelectedItem();
         
                try{
           // Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
       // Connection con = DriverManager.getConnection("jdbc:odbc:ins");
           Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/irctc?zeroDateTimeBehavior=convertToNull","root","123456");
            Statement stmt=con.createStatement();
            String sql="Insert into T_T2 values('"+L2.getText()+"','"+tn+"','"+not+"',"+total+")";
           stmt.executeUpdate(sql);
          }
       catch(Exception ex)
       {
       JOptionPane.showMessageDialog(null,ex.getMessage());
       }
                int pm=0;
pm=total;
PAYMENT RR=new PAYMENT(pm, L2.getText());
     RR.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        new TOURIST_TRAIN(L2.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void NTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T_T2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T_T2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T_T2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T_T2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T_T2(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FPP;
    private javax.swing.JTextArea INFO;
    private javax.swing.JLabel L2;
    private javax.swing.JTextField NT;
    private javax.swing.JLabel P0;
    private javax.swing.JLabel P1;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P3;
    private javax.swing.JLabel P4;
    private javax.swing.JComboBox<String> ST;
    private javax.swing.JTextField TF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
