
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAMYAK & ATISHAY
 */
public class T_T3 extends javax.swing.JFrame {

    /**
     * Creates new form T_T3
     */
    public T_T3(String un) {
        initComponents();
        L2.setText(un);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TP1 = new javax.swing.JRadioButton();
        TP2 = new javax.swing.JRadioButton();
        TP3 = new javax.swing.JRadioButton();
        TP4 = new javax.swing.JRadioButton();
        TP5 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        INFO = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        L2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1282, 683));
        setMinimumSize(new java.awt.Dimension(1282, 683));
        setPreferredSize(new java.awt.Dimension(1282, 683));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(TP1);
        TP1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TP1.setText("GANGA SNAN SPECIAL YATRA");
        TP1.setOpaque(false);
        TP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP1ActionPerformed(evt);
            }
        });
        getContentPane().add(TP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 440, -1));

        buttonGroup1.add(TP2);
        TP2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TP2.setText("VACATION SPECIAL YATRA");
        TP2.setOpaque(false);
        TP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP2ActionPerformed(evt);
            }
        });
        getContentPane().add(TP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 440, -1));

        buttonGroup1.add(TP3);
        TP3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TP3.setText("DAKSHIN BHARAT YATRA");
        TP3.setOpaque(false);
        TP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP3ActionPerformed(evt);
            }
        });
        getContentPane().add(TP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 440, -1));

        buttonGroup1.add(TP4);
        TP4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TP4.setText("JYOTIRLING YATRA");
        TP4.setOpaque(false);
        TP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP4ActionPerformed(evt);
            }
        });
        getContentPane().add(TP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 440, -1));

        buttonGroup1.add(TP5);
        TP5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TP5.setText("RAJASTHAN SPECIAL");
        TP5.setOpaque(false);
        TP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP5ActionPerformed(evt);
            }
        });
        getContentPane().add(TP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 440, -1));

        INFO.setEditable(false);
        INFO.setColumns(20);
        INFO.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        INFO.setRows(5);
        jScrollPane1.setViewportView(INFO);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 700, 350));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 282, 1120, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bharat2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 200, 210));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RR.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 50, 240, 190));

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 60)); // NOI18N
        jLabel1.setText("Bharat darshan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 660, 120));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel4.setText("feel the goodness of India");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 690, 60));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("SELECT YOUR PACKAGE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 230, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("TOTAL FAIR");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 270, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("NO. OF TICKETS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 270, 40));

        jButton1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jButton1.setText("CLICK HERE TO CONFIRM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 500, 60));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 310, 30));

        t2.setEditable(false);
        t2.setMaximumSize(new java.awt.Dimension(1282, 683));
        t2.setMinimumSize(new java.awt.Dimension(1282, 683));
        t2.setPreferredSize(new java.awt.Dimension(1282, 683));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 310, 30));

        L2.setBackground(new java.awt.Color(255, 255, 255));
        L2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        L2.setOpaque(true);
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 190, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("USERNAME");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 180, 30));

        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("<<back to tourist trains");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 150, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/596963.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jLabel10.setMaximumSize(null);
        jLabel10.setMinimumSize(null);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int fr=0;String i;String cn;

    private void TP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP1ActionPerformed
        if(TP1.isSelected())
        {
        i="GANGA SNAN SPECIAL YATRA"+"\n"+"Duration:8 Nights/9 Days"+"\n"+"City: HARIDWAR / RISHIKESH / VARANASI"+"\n"+"FAIR PER PERSON-8550RS"+"\n"+"Origin:GUWAHATI";
       fr=8550;cn="GANGA SNAN SPECIAL YATRA";
       INFO.setText(""+i);
        }
        
    }//GEN-LAST:event_TP1ActionPerformed

    private void TP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP2ActionPerformed
        // TODO add your handling code here:
          if(TP2.isSelected())
        {
        i="VACATION SPECIAL"+"\n"+"Duration:12 Nights/13 Days"+"\n"+"City: AGRA / AMRITSAR / DELHI / GOA / JAIPUR"+"\n"+"FAIR PER PERSON-13230RS"+"\n"+"Origin:MADURAI";
       fr=13230;cn="VACATION SPECIAL";
        INFO.setText(""+i);
        }
    }//GEN-LAST:event_TP2ActionPerformed

    private void TP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP3ActionPerformed
        // TODO add your handling code here:
          if(TP3.isSelected())
        {
        i="DAKSHIN BHARAT YATRA"+"\n"+"Duration:12 Nights/13 Days"+"\n"+"City: KANYAKUMARI / KOVALAM / MADURAI / MALLIKARJUN / RAMESWARAM "+"\n"+"/ TIRUCHIRAPALLI / TIRUPATI / TRIVANDRUM"+"\n"+"\"FAIR PER PERSON-13280RS"+"\n"+"Origin:GORAKHPUR";
       fr=13280;cn=" DAKSHIN BHARAT YATRA";
        INFO.setText(""+i);
        }
    }//GEN-LAST:event_TP3ActionPerformed

    private void TP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP4ActionPerformed
        // TODO add your handling code here:
          if(TP4.isSelected())
        {
        i="JYOTIRLING YATRA"+"\n"+"Duration:10 Nights/11 Days"+"\n"+"City: AHMEDABAD / BHIMSHANKAR /"+"\n"+" DWARKA / GRISHNESHWAR / NAGESHWAR / OMKARESHWAR"+"\n"+" / SOMNATH / STATUE OF UNITY / UJJAIN"+"\n"+"FAIR PER PERSON-10550RS"+"\n"+"Origin:JAIPUR";
       fr=10550;cn=" JYOTIRLING YATRA";
        INFO.setText(""+i);
        }
    }//GEN-LAST:event_TP4ActionPerformed

    private void TP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP5ActionPerformed
        // TODO add your handling code here:
          if(TP5.isSelected())
        {
        i="RAJASTHAN SPECIAL"+"\n"+"Duration:10 Nights/11 Days"+"\n"+"City: AMRITSAR / HARIDWAR / JAIPUR / MATHURA / UDAIPUR / VAISHNO DEVI"+"\n"+"FAIR PER PERSON-10395RS"+"\n"+"Origin:SOLAPUR";
       fr=10395;cn=" RAJASTHAN SPECIAL";
        INFO.setText(""+i);
        }
    }//GEN-LAST:event_TP5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int c,d=0;
        c=Integer.parseInt(t1.getText());
        if(c<=10)
        {
        d=c*fr;
        t2.setText(""+d);
        
       
        }
        else
        {
         JOptionPane.showMessageDialog(null,"booking cannot be done for more than one ticket");
        }
                  try{
           // Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
       // Connection con = DriverManager.getConnection("jdbc:odbc:ins");
           Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/irctc?zeroDateTimeBehavior=convertToNull","root","123456");
            Statement stmt=con.createStatement();
            String sql="Insert into T_T3 values('"+L2.getText()+"','"+cn+"','"+c+"',"+d+")";
           stmt.executeUpdate(sql);
          }
       catch(Exception ex)
       {
       JOptionPane.showMessageDialog(null,ex.getMessage());
       }
        
        
        int pm=0;
pm=d;
PAYMENT RR=new PAYMENT(pm ,L2.getText());
     RR.setVisible(true);     this.dispose();

        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        new TOURIST_TRAIN(L2.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T_T3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T_T3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T_T3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T_T3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T_T3(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea INFO;
    private javax.swing.JLabel L2;
    private javax.swing.JRadioButton TP1;
    private javax.swing.JRadioButton TP2;
    private javax.swing.JRadioButton TP3;
    private javax.swing.JRadioButton TP4;
    private javax.swing.JRadioButton TP5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
