
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAMYAK & ATISHAY
 */
public class TICKET_INFO extends javax.swing.JFrame {

    /**
     * Creates new form TICKET_INFO
     */
    public TICKET_INFO(int fa,String un1,String dob,String src,String dst,String trn,int r) {
        initComponents();
       jLabel2.setText(""+fa); ;L3.setText(""+un1);L4.setText(""+dob);L5.setText(""+src);L6.setText(""+dst);L7.setText(""+trn);l12.setText(""+r);
        UIManager.put("OptionPane.messageFont", new Font("TIMES NEW ROMAN", Font.BOLD, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA1 = new javax.swing.JTextArea();
        L3 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("TICKET INFO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 360, 58));

        l2.setVisible(false);
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setText("BOOK TICKET");
        jButton1.setMaximumSize(new java.awt.Dimension(998, 676));
        jButton1.setMinimumSize(new java.awt.Dimension(998, 676));
        jButton1.setPreferredSize(new java.awt.Dimension(998, 676));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 920, 60));

        TA1.setEditable(false);
        TA1.setColumns(20);
        TA1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        TA1.setRows(5);
        jScrollPane1.setViewportView(TA1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 920, 500));

        L3.setVisible(false);
        getContentPane().add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        L6.setVisible(false);
        getContentPane().add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        L5.setVisible(false);
        getContentPane().add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        L4.setVisible(false);
        getContentPane().add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        L7.setVisible(false);
        getContentPane().add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        l12.setVisible(false);
        getContentPane().add(l12, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, 60, 30));

        jLabel2.setVisible(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/159977.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 680));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

int rand=0;
       long rand1=0;
 int max1 = 150;
        int min1 = 5;
        int range1 = max1 - min1 + 1;
        for (int i = 0; i < 10; i++) {
             rand = (int)(Math.random() * range1) + min1;
         }
       
        long maxi;
        maxi=999999999;
        long mini = 100000000;
        long rangei = maxi - mini + 1;
        for (int ii = 0; ii < 10; ii++) 
        {
             rand1 = (long)(Math.random() * rangei) + mini;
        }
        
TA1.append("      YOUR TICKET INFO        " + "\n" +"USER ID:  "+L3.getText()+ "\n" +"PNR NO:  "+ rand1 + "\n" +"NUMBER OF PASSENGERS:  " +l12.getText()+"\n"+  "SOURCE STATION:  "+L5.getText()+"\n"+  "DESTINATION STATION:  "+L6.getText()+"\n"+ "TRAIN NAME:  " +L7.getText()+"\n"+"TICKET STATUS:  " + "WL"+ (int) rand + "\n"+"DATE OF JOURNEY:  "+L4.getText()+"\n"+ "TOTAL FARE:  " + jLabel2.getText() );

       try{
           // Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
       // Connection con = DriverManager.getConnection("jdbc:odbc:ins");
           Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/irctc?zeroDateTimeBehavior=convertToNull","root","123456");
            Statement stmt=con.createStatement();
            String sql="Insert into book_ticket values('"+L3.getText()+"','"+L4.getText()+"',"+rand1+","+l12.getText()+",'"+L5.getText()+"','"+L6.getText()+"',"+jLabel2.getText()+",'"+L7.getText()+"','"+"WL"+ (int) rand+"')";
           
           
             
        stmt.executeUpdate(sql);
        
       }
       catch(Exception ex)
       {
       JOptionPane.showMessageDialog(null,ex.getMessage());
       }
       finally
       {int pm=Integer.parseInt(jLabel2.getText());
        JOptionPane.showMessageDialog(null,"BOOK TICKET SUCCESFULL.........");
        new PAYMENT(pm,L3.getText()).setVisible(true);
        this.dispose();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TICKET_INFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TICKET_INFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TICKET_INFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TICKET_INFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TICKET_INFO(0,null,null,null,null,null,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JTextArea TA1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l2;
    // End of variables declaration//GEN-END:variables
}
